apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    spec:
      containers:      
      - name: hello
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - date; echo Hello ${userName} from the Kubernetes cluster ${clusterId}
      restartPolicy: OnFailure
  backoffLimit: 3
